### ISSUE TITLE
BUG - Bad chars

### ISSUE THREAD

**Issue by truefriend-cz** [leminhthanh1998/LMTAntiLogger#1]
Hi. If typing show bad character symbols from diacritics.

**Comment by leminhthanh1998** [comment]
> Hi. If typing show bad character symbols from diacritics.

Hi, sorry for the late reply. You can download the version 3.9.1. This version fix all bug in Anti Keylogger.

**Comment by truefriend-cz** [comment]
That's ok but the problem remained. I used version 3.9.3 and the problem is still the same.
My language is Czech and after turning on the item below Anti Logger will start typing characters that are not Czech.

Left side is czech character = on left side Anti Logger character
`
č = è,
ř = ø,
ž = ,
ý = ý,
á = á,
í = í,
ě = ì,
š = ,
ú = ú,
ů = ů
`
and... virtual keyboard contains only characters without hooks and commas.

**Comment by leminhthanh1998** [comment]
Hi, sorry for late reply. Now my app only support English keyboard layout.
